---
name: 'Dokku'
description: 'Deploys an app via git push to a Dokku instance'
author: 'Dokku'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  deploy_branch:
    description: 'The branch to be deployed when pushing to Dokku (default: master)'
    required: false
    default: "master"
  remote_url:
    description: "The dokku app's git repository url (in SSH format)"
    required: true
  ssh_host_key:
    description: 'The results of running ssh-keyscan -t rsa $HOST.'
    required: false
    default: ""
  ssh_private_key:
    description: 'A private SSH key that has push acces to your Dokku instance'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/bin/entrypoint'
  post-entrypoint: '/bin/dokku-unlock'
  post-if: cancelled()
  env:
    SSH_HOST_KEY: ${{ inputs.ssh_host_key }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    REMOTE_URL: ${{ inputs.remote_url }}
    DEPLOY_BRANCH: ${{ inputs.deploy_branch }}
