---
name: 'Dokku'
description: 'Official Github Action for deploying apps to a Dokku installation via git push'
author: 'Dokku'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  branch:
    description: 'The branch to be deployed when pushing to Dokku (default: master)'
    required: false
    default: "master"
  push_flags:
    description: "The dokku app's git repository url (in SSH format)"
    required: true
  remote_url:
    description: "A string containing a set of flags to set on push"
    required: false
  ssh_host_key:
    description: 'The results of running ssh-keyscan -t rsa $HOST.'
    required: false
    default: ""
  ssh_private_key:
    description: 'A private SSH key that has push acces to your Dokku instance'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/bin/entrypoint'
  post-entrypoint: '/bin/dokku-unlock'
  post-if: cancelled()
  env:
    BRANCH: ${{ inputs.branch }}
    PUSH_FLAGS: ${{ inputs.push_flags }}
    REMOTE_URL: ${{ inputs.remote_url }}
    SSH_HOST_KEY: ${{ inputs.ssh_host_key }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
