---
name: 'lint'

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          MARKDOWN_CONFIG_FILE: .github/markdown-lint-config.yml
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
